export const deliveryCities = [
  "Agalawatta",
  "Agunukolapelessa",
  "Ahangama",
  "Ahungalla",
  "Akkaraipattu",
  "Akmeemana",
  "Akuressa",
  "Alawwa",
  "Aluthgama",
  "Ambalangoda",
  "Ambalantota",
  "Ambepussa",
  "Ampara",
  "Anamaduwa",
  "Angunakolapelessa",
  "Anuradhapura",
  "Aralaganwila",
  "Athurugiriya",
  "Avissawella",
  "Baddegama",
  "Badulla",
  "Balangoda",
  "Bandaragama",
  "Bandarawela",
  "Batticaloa",
  "Bentota",
  "Beruwala",
  "Bibile",
  "Bingiriya",
  "Chavakachcheri",
  "Chilaw",
  "Colombo",
  "Dankotuwa",
  "Dehiwala",
  "Deniyaya",
  "Dikwella",
  "Dambulla",
  "Embilipitiya",
  "Ella",
  "Elpitiya",
  "Galagedara",
  "Galgamuwa",
  "Galle",
  "Gampaha",
  "Ganemulla",
  "Hambantota",
  "Hatton",
  "Hikkaduwa",
  "Homagama",
  "Horana",
  "Ingiriya",
  "Ja-Ela",
  "Jaffna",
  "Kadawatha",
  "Kaduwela",
  "Kalmunai",
  "Kalutara",
  "Kandy",
  "Kantale",
  "Kataragama",
  "Katunayake",
  "Kelaniya",
  "Kegalle",
  "Kilinochchi",
  "Kiribathgoda",
  "Kuliyapitiya",
  "Kurunegala",
  "Maharagama",
  "Mahiyanganaya",
  "Mannar",
  "Matale",
  "Matara",
  "Mathugama",
  "Medawachchiya",
  "Minuwangoda",
  "Monaragala",
  "Moratuwa",
  "Mullaitivu",
  "Nawalapitiya",
  "Negombo",
  "Nikaweratiya",
  "Nittambuwa",
  "Nuwara Eliya",
  "Panadura",
  "Pelmadulla",
  "Peradeniya",
  "Piliyandala",
  "Polgahawela",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Ragama",
  "Tangalle",
  "Thissamaharama",
  "Trincomalee",
  "Vavuniya",
  "Wadduwa",
  "Warakapola",
  "Wariyapola",
  "Wattala",
  "Weligama",
  "Wellawaya",
  "Wennappuwa",
  "Yakkala",
] as const;

// Kept separate from deliveryCities so checkout can continue to offer the
// complete service-area list while delivery prediction stays easy to scan.
export const mainDeliveryCities = [
  "Colombo",
  "Kandy",
  "Galle",
  "Jaffna",
  "Negombo",
  "Kurunegala",
  "Anuradhapura",
  "Trincomalee",
  "Batticaloa",
  "Matara",
  "Ratnapura",
  "Badulla",
  "Nuwara Eliya",
  "Hambantota",
  "Kalutara",
  "Gampaha",
  "Kegalle",
  "Puttalam",
  "Vavuniya",
  "Polonnaruwa",
  "Ampara",
  "Mannar",
  "Mullaitivu",
  "Kilinochchi",
  "Monaragala",
  "Matale",
] as const;

export const locationTypes = [
  "House",
  "Apartment",
  "Office",
  "Hospital",
  "School",
  "Funeral Home",
  "Wedding Reception",
  "Other(Including Hotels)",
] as const;

export function toCommerceLocationType(value?: string) {
  if (!value) {
    return "house";
  }

  return value
    .toLowerCase()
    .replace(/\([^)]*\)/g, "")
    .trim()
    .replace(/\s+/g, "_");
}
