-- Kapruka product image embeddings for GenieAI.
-- Run once in Supabase Dashboard > SQL Editor before the image backfill.
--
-- This is intentionally separate from kapruka_gift_product_embeddings, which
-- stores one 384-dimensional text embedding per product. A product may have
-- several images, so this table stores one 512-dimensional CLIP embedding per
-- unique product image.

create extension if not exists vector with schema extensions;

create table if not exists public.kapruka_gift_product_image_embeddings (
  assigned_category text not null,
  product_id text not null,
  image_key text not null,
  image_url text not null,
  image_position integer not null default 0,
  is_primary boolean not null default false,
  image_hash text not null,
  embedding extensions.vector(512) not null,
  embedding_model text not null,
  source_updated_at timestamptz,
  embedded_at timestamptz not null default now(),

  constraint kapruka_gift_product_image_embeddings_pkey
    primary key (assigned_category, product_id, image_key),
  constraint kapruka_gift_product_image_embeddings_source_fkey
    foreign key (assigned_category, product_id)
    references public.kapruka_gift_products (assigned_category, product_id)
    on delete cascade,
  constraint kapruka_gift_product_image_embeddings_image_key_check
    check (image_key <> ''),
  constraint kapruka_gift_product_image_embeddings_image_url_check
    check (image_url <> ''),
  constraint kapruka_gift_product_image_embeddings_position_check
    check (image_position >= 0)
);

comment on table public.kapruka_gift_product_image_embeddings is
  'One normalized 512-dimensional CLIP embedding per unique Kapruka product image.';

comment on column public.kapruka_gift_product_image_embeddings.image_key is
  'Stable SHA-256 hex digest of the normalized image URL, generated by the backfill.';

comment on column public.kapruka_gift_product_image_embeddings.image_hash is
  'SHA-256 hex digest of the downloaded image bytes; used to detect changed images.';

create index if not exists kapruka_gift_product_image_embeddings_vector_idx
  on public.kapruka_gift_product_image_embeddings
  using hnsw (embedding vector_cosine_ops);

create index if not exists kapruka_gift_product_image_embeddings_product_idx
  on public.kapruka_gift_product_image_embeddings (assigned_category, product_id);

create index if not exists kapruka_gift_product_image_embeddings_model_idx
  on public.kapruka_gift_product_image_embeddings (embedding_model);

alter table public.kapruka_gift_product_image_embeddings enable row level security;
revoke all on table public.kapruka_gift_product_image_embeddings from anon, authenticated;

-- Canonical source for the backfill. It combines image_url with every element
-- in images, accepts both string URLs and common object shapes, and removes
-- duplicate URLs within each product. image_position 0 is reserved for the
-- product's image_url; entries from images start at 1.
create or replace view public.kapruka_gift_product_image_urls
with (security_invoker = true)
as
with candidate_urls as (
  select
    p.assigned_category,
    p.product_id,
    p.image_url,
    0::integer as image_position,
    true as is_primary,
    p.updated_at as source_updated_at
  from public.kapruka_gift_products p

  union all

  select
    p.assigned_category,
    p.product_id,
    case jsonb_typeof(item.value)
      when 'string' then item.value #>> '{}'
      when 'object' then coalesce(
        item.value ->> 'image_url',
        item.value ->> 'url',
        item.value ->> 'src'
      )
      else null
    end as image_url,
    item.ordinality::integer as image_position,
    false as is_primary,
    p.updated_at as source_updated_at
  from public.kapruka_gift_products p
  cross join lateral jsonb_array_elements(p.images)
    with ordinality as item(value, ordinality)
),
ranked_urls as (
  select
    assigned_category,
    product_id,
    btrim(image_url) as image_url,
    image_position,
    is_primary,
    source_updated_at,
    row_number() over (
      partition by assigned_category, product_id, btrim(image_url)
      order by is_primary desc, image_position
    ) as duplicate_rank
  from candidate_urls
  where image_url is not null
    and btrim(image_url) <> ''
)
select
  assigned_category,
  product_id,
  image_url,
  image_position,
  is_primary,
  source_updated_at
from ranked_urls
where duplicate_rank = 1;

comment on view public.kapruka_gift_product_image_urls is
  'Deduplicated image_url and images[] URLs for every Kapruka gift product.';

revoke all on table public.kapruka_gift_product_image_urls from anon, authenticated;
grant select on table public.kapruka_gift_product_image_urls to service_role;

create or replace function public.match_kapruka_gift_product_images(
  query_embedding extensions.vector(512),
  match_count integer default 20,
  filter_category text default null,
  min_price numeric default null,
  max_price numeric default null,
  filter_embedding_model text default 'openai/clip-vit-base-patch32'
)
returns table (
  assigned_category text,
  product_id text,
  name text,
  summary text,
  description text,
  price_amount numeric,
  currency text,
  in_stock boolean,
  stock_level text,
  image_url text,
  images jsonb,
  kapruka_category jsonb,
  product_url text,
  matched_image_url text,
  similarity double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  with ranked_images as (
    select
      e.assigned_category,
      e.product_id,
      e.image_url as matched_image_url,
      1 - (e.embedding OPERATOR(extensions.<=>) query_embedding) as similarity,
      row_number() over (
        partition by e.assigned_category, e.product_id
        order by e.embedding OPERATOR(extensions.<=>) query_embedding
      ) as product_image_rank
    from public.kapruka_gift_product_image_embeddings e
    where e.embedding_model = filter_embedding_model
  )
  select
    p.assigned_category,
    p.product_id,
    p.name,
    p.summary,
    p.description,
    p.price_amount,
    p.currency,
    p.in_stock,
    p.stock_level,
    p.image_url,
    p.images,
    p.kapruka_category,
    p.product_url,
    r.matched_image_url,
    r.similarity
  from ranked_images r
  join public.kapruka_gift_products p
    on p.assigned_category = r.assigned_category
   and p.product_id = r.product_id
  where r.product_image_rank = 1
    and p.in_stock is true
    and (filter_category is null or p.assigned_category = filter_category)
    and (min_price is null or p.price_amount >= min_price)
    and (max_price is null or p.price_amount <= max_price)
  order by r.similarity desc
  limit greatest(1, least(match_count, 60));
$$;

revoke all on function public.match_kapruka_gift_product_images(
  extensions.vector, integer, text, numeric, numeric, text
) from public, anon, authenticated;

grant execute on function public.match_kapruka_gift_product_images(
  extensions.vector, integer, text, numeric, numeric, text
) to service_role;
