import Image from "next/image";
import { cleanProductDescription } from "@/lib/productDescription";
import { V3Icon } from "./Icon";
import type { GenieProduct } from "./types";

export function ProductDialog({ formatPrice, onClose, product }: { formatPrice: (price: number, currency: string) => string; onClose: () => void; product: GenieProduct | null }) {
  if (!product) return null;
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-[#0A1F3A]/45 p-4 backdrop-blur-sm"><button type="button" onClick={onClose} className="absolute inset-0" aria-label="Close product details"/><section role="dialog" aria-modal="true" aria-labelledby="v3-product-title" className="relative z-10 max-h-full w-full max-w-3xl overflow-y-auto rounded-[18px] border border-[#E4E1D8] bg-white shadow-[0_16px_40px_-16px_rgba(10,31,58,.4)]"><header className="flex items-center justify-between border-b border-[#E4E1D8] p-5"><div><p className="text-[11px] font-bold uppercase tracking-[1.1px] text-[#B3872F]">Product details</p><h2 id="v3-product-title" className="mt-1 font-serif text-xl font-semibold text-[#0A1F3A]">{product.name}</h2></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg border border-[#E4E1D8]" aria-label="Close product details"><V3Icon name="x" className="h-4 w-4" /></button></header><div className="grid gap-5 p-5 md:grid-cols-[280px_1fr]"><div className="relative aspect-square overflow-hidden rounded-[16px] bg-[#E7EEF7]"><Image src={product.imageUrl} alt={product.name} fill unoptimized sizes="280px" className="object-cover" /></div><div><p className="rounded-xl bg-[#FAF7F1] p-3 text-lg font-bold text-[#123661]">{formatPrice(product.price,product.currency)}</p><h3 className="mt-5 text-sm font-bold text-[#0A1F3A]">Description</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#5B6B7A]">{cleanProductDescription(product.description)}</p></div></div></section></div>;
}
